name: Playwright E2E Summary
description: Generate Playwright E2E summary artifacts, append markdown summary, and upload report artifacts.

inputs:
  report_json_path:
    description: Path to Playwright JSON report.
    required: true
  summary_json_path:
    description: Output path for generated JSON summary.
    required: true
  summary_md_path:
    description: Output path for generated Markdown summary.
    required: true
  summary_title:
    description: Title used in generated markdown summary.
    required: true
  artifact_summary_name:
    description: Artifact name for summary JSON/Markdown files.
    required: true
  artifact_json_name:
    description: Artifact name for raw Playwright JSON report.
    required: true
  top_slow:
    description: Number of slow tests to include.
    required: false
    default: "10"
  slow_threshold_ms:
    description: Slow test threshold in milliseconds.
    required: false
    default: "5000"

runs:
  using: composite
  steps:
    - name: Generate Playwright E2E summary
      shell: bash
      run: |
        node scripts/ci/summarize-playwright-json.mjs \
          --input "${{ inputs.report_json_path }}" \
          --output "${{ inputs.summary_json_path }}" \
          --markdown-output "${{ inputs.summary_md_path }}" \
          --title "${{ inputs.summary_title }}" \
          --top-slow "${{ inputs.top_slow }}" \
          --slow-threshold-ms "${{ inputs.slow_threshold_ms }}"

    - name: Append Playwright E2E summary to step summary
      if: always()
      shell: bash
      run: |
        if [ -n "${GITHUB_STEP_SUMMARY:-}" ] && [ -f "${{ inputs.summary_md_path }}" ]; then
          cat "${{ inputs.summary_md_path }}" >> "$GITHUB_STEP_SUMMARY"
        fi

    - name: Upload Playwright E2E summary
      if: always()
      uses: ./.github/actions/artifact-upload
      with:
        artifact_name: ${{ inputs.artifact_summary_name }}
        artifact_path: |
          ${{ inputs.summary_json_path }}
          ${{ inputs.summary_md_path }}

    - name: Upload Playwright E2E JSON report
      if: always()
      uses: ./.github/actions/artifact-upload
      with:
        artifact_name: ${{ inputs.artifact_json_name }}
        artifact_path: ${{ inputs.report_json_path }}
