export const SANDBOX_EXECUTION_ERROR_CODES = {
  EGRESS_POLICY_DENY: 'SANDBOX_EXECUTION_EGRESS_POLICY_DENY',
  EGRESS_PROFILE_REQUIRED: 'SANDBOX_EXECUTION_EGRESS_PROFILE_REQUIRED',
  EGRESS_PROFILE_UNCONFIGURED: 'SANDBOX_EXECUTION_EGRESS_PROFILE_UNCONFIGURED',
  EGRESS_PROVIDER_INVALID: 'SANDBOX_EXECUTION_EGRESS_PROVIDER_INVALID',
  INVALID_INPUT: 'SANDBOX_EXECUTION_INVALID_INPUT',
  LIMIT_PROFILE_REQUIRED: 'SANDBOX_EXECUTION_LIMIT_PROFILE_REQUIRED',
  LIMIT_PROFILE_UNCONFIGURED: 'SANDBOX_EXECUTION_LIMIT_PROFILE_UNCONFIGURED',
  LIMITS_EXCEEDED: 'SANDBOX_EXECUTION_LIMITS_EXCEEDED',
  LIMITS_INVALID_REQUEST: 'SANDBOX_EXECUTION_LIMITS_INVALID_REQUEST',
  OPERATION_INVALID: 'SANDBOX_EXECUTION_OPERATION_INVALID',
  PATH_NOT_FOUND: 'SANDBOX_EXECUTION_PATH_NOT_FOUND',
  PROCESS_FAILED: 'SANDBOX_EXECUTION_PROCESS_FAILED',
  SANDBOX_EXPIRED: 'SANDBOX_EXECUTION_SANDBOX_EXPIRED',
  SANDBOX_NOT_FOUND: 'SANDBOX_EXECUTION_SANDBOX_NOT_FOUND',
  TIMEOUT: 'SANDBOX_EXECUTION_TIMEOUT',
  UNKNOWN_ERROR: 'SANDBOX_EXECUTION_UNKNOWN_ERROR',
} as const;

export type SandboxExecutionErrorCode =
  (typeof SANDBOX_EXECUTION_ERROR_CODES)[keyof typeof SANDBOX_EXECUTION_ERROR_CODES];

const SANDBOX_EXECUTION_ERROR_CODE_SET = new Set<string>(
  Object.values(SANDBOX_EXECUTION_ERROR_CODES),
);

export const isSandboxExecutionErrorCode = (
  value: unknown,
): value is SandboxExecutionErrorCode =>
  typeof value === 'string' && SANDBOX_EXECUTION_ERROR_CODE_SET.has(value);
