name: Artifact Upload
description: Upload a single artifact with configurable not-found behavior.

inputs:
  artifact_name:
    description: Artifact name.
    required: true
  artifact_path:
    description: Artifact path or directory.
    required: true
  if_no_files_found:
    description: Behavior when no files are found (error, warn, ignore).
    required: false
    default: ignore

runs:
  using: composite
  steps:
    - name: Upload artifact
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.artifact_name }}
        path: ${{ inputs.artifact_path }}
        if-no-files-found: ${{ inputs.if_no_files_found }}
